version: "3.9"
services:
  config_server:
    container_name: config-server
    image: apolos7/config-server:latest
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
    networks:
      - msvc
    restart: always

networks:
  msvc:
    name: msvc